---

- name: Install software I want
  yum: pkg={{ item }} state=latest
  with_items:
    - net-tools
    - vim-enhanced
    - tmux
    - git

- name: Checkout my dotfiles repo
  git: repo=https://github.com/rothgar/dotfiles.git dest=/home/rothgar/.dotfiles

- name: Configure dotfiles
  command: /home/rothgar/.dotfiles/bootstrap.sh
  ignore_errors: True

- name: Make mount folder
  file: path=/mnt/cdrom state=directory owner=root group=root

- name: Install VMware Tools (make sure VMware Tools iso is mounted)
  mount: name=/mnt/cdrom src=/dev/cdrom fstype=iso9660 opts=ro state=present
  register: result
  until: result.stdout.find('VMware') != -1
  retries: 10
  delay: 10
  when: ansible_virtualization_type == "VMware"

- name: Extract installer
  command: /usr/bin/tar -xzf /mnt/cdrom/VMwareTools*.tar.gz -C /tmp/
  when: ansible_virtualization_type == "VMware" and result.stout.find("VMware Tools") != -1

- name: Run VMware installer
  command: /tmp/vmware-tools-distrib/vmware-install.pl -d
  when: ansible_virtualization_type == "VMware"
